### ISSUE TITLE
Question.

### ISSUE THREAD

**Issue by OneKoin** [northwood-studios/SCPSL-Translations#505] opened 2020-06-14 05:23 UTC
I've uploaded korean translation about 1 month and half ago and there were reviews by users and @Tychus-Xiaoyi. I know that there are no one who can check korean translation, but why is it taking too long?

**Comment by ConnorTheCone** [comment] 2020-06-15 06:28
Seems like your translation has conflicts with credits.txt. Anyways sometimes they take some time to review the translations, i'm also wating for the ES translation and some guys had pull request from 2019 for the MP2.

**Comment by Dat-Joseph** [comment] 2020-06-15 08:56
Hey, please dont think we dont care about the translation repo. We really try to keep it up to date but due to lack of native translators, it can take time. Sometimes like connor says even months. We have to make sure that the translations you players suggest are correct (we had some users who submitted wrong or even insulting translations in foreign languages)

**Comment by OneKoin** [comment] 2020-06-15 08:58
> Hey, please dont think we dont care about the translation repo. We really try to keep it up to date but due to lack of native translators, it can take time. Sometimes like connor says even months. We have to make sure that the translations you players suggest are correct (we had some users who submitted wrong or even insulting translations in foreign languages)

Thanks for replying. I'd better wait.

**Comment by ConnorTheCone** [comment] 2020-06-15 09:53
> 
> 
> Hey, please dont think we dont care about the translation repo. We really try to keep it up to date but due to lack of native translators, it can take time. Sometimes like connor says even months. We have to make sure that the translations you players suggest are correct (we had some users who submitted wrong or even insulting translations in foreign languages)

Well, in my case i can confirm whay my translation is not troll or whatever (Of course that's not a neutral opinion i guess). I don't have any problem with waiting, in fact, i update the pull request when i see some update on the english texts. I just want to recive an answer before the scopo goes live because there are some things wrong on the current ES translations, something like the Whitelist error and the 939 description.

**Comment by Rnen** [comment] 2020-06-15 12:45
I'll make sure to bring this up

**Comment by ConnorTheCone** [comment] 2020-06-15 12:52
> 
> 
> I'll make sure to bring this up

Thanks evan

**Comment by Dat-Joseph** [comment] 2020-06-15 13:14
Changes are usually in the next published Beta Version :)

**Comment by Dat-Joseph** [comment] 2020-06-15 13:18
> I've uploaded korean translation about 1 month and half ago and there were reviews by users and I know that there are no one who can check korean translation, but why is it taking too long?

You uploaded another Korean Version. This is pretty good. Can you do us a favor and look over the oldest PR we have: https://github.com/northwood-studios/SCPSL-Translations/pull/266/files?file-filters%5B%5D=#

It is the korean you are talking about. If its okay by you, we will merge it into our repo. This also means that you would need to look over yours and maybe create a new one based of the previous pull request.  I cant speak korean but i'll try to resolve your issue asap 👍

**Comment by OneKoin** [comment] 2020-06-15 13:28
> > I've uploaded korean translation about 1 month and half ago and there were reviews by users and I know that there are no one who can check korean translation, but why is it taking too long?
> 
> You uploaded another Korean Version. This is pretty good. Can you do us a favor and look over the oldest PR we have: https://github.com/northwood-studios/SCPSL-Translations/pull/266/files?file-filters%5B%5D=#
> 
> It is the korean you are talking about. If its okay by you, we will merge it into our repo. This also means that you would need to look over yours and maybe create a new one based of the previous pull request.  I cant speak korean but i'll try to resolve your issue asap 👍 
> 
> 

I've checked the PR you've said. And it's fine with me. Some parts of those previous PR is nice so if you merge it today or someday, i'll look over mine again, and create new one asap. Thanks for your help 😁

**Comment by Dat-Joseph** [comment] 2020-06-15 13:32
Thank you for helping us! 👍 
Of course we will merge it today. If you have any other issues or questions, feel free to ask 😄 
I will keep this issue open for further discussion.

**Comment by Dat-Joseph** [comment] 2020-06-15 13:34
Little update: its been approved and merged 😀

**Comment by OneKoin** [comment] 2020-06-15 13:36
@Dat-Joseph Now I'm planning to update the translation my next day, should I create new PR or update on previous PR?

**Comment by Dat-Joseph** [comment] 2020-06-15 13:40
From my perspective its always better to first download the old fork repo to your local machine. You keep your already made, but not merged, translations like that. Then create a complete fresh and new fork of our repo. Then edit the files online one by one which needs correction and or additions. 
This is easier than rewriting everything and resolving conflicts between forks/repo's. However this is just my point of view. You can do as you like.

**Comment by OneKoin** [comment] 2020-06-15 13:42
Thanks again :)

**Comment by Dat-Joseph** [comment] 2020-06-15 13:42
No problem 😃

**Closed** 2020-07-19 23:57 UTC
